# Generated by Django 4.2.5 on 2025-06-18 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_image',
            new_name='image',
        ),
        migrations.AlterModelTable(
            name='item',
            table='items',
        ),
    ]
