# Generated by Django 4.2.23 on 2025-07-04 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_order_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, unique=True, verbose_name='プロモーションコード')),
                ('discount', models.IntegerField(default=100, verbose_name='割引額')),
                ('max_uses', models.IntegerField(default=1, verbose_name='最大使用回数')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 'promotion_codes',
            },
        ),
        migrations.CreateModel(
            name='OrderPromotionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_count', models.IntegerField(default=0, verbose_name='使用回数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.order', verbose_name='注文')),
                ('promotion_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_promotion_codes', to='promotion_code.promotioncode', verbose_name='プロモーションコード')),
            ],
            options={
                'db_table': 'order_promotion_codes',
                'unique_together': {('promotion_code', 'order')},
            },
        ),
    ]
