# Generated by Django 4.2.23 on 2025-07-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion_code', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotioncode',
            name='max_uses',
        ),
        migrations.AddField(
            model_name='promotioncode',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='使用済'),
        ),
        migrations.DeleteModel(
            name='OrderPromotionCode',
        ),
    ]
