# Generated by Django 4.2.23 on 2025-07-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount_amount',
            field=models.IntegerField(default=0, verbose_name='割引額'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(max_length=40, unique=True, verbose_name='セッションキー'),
        ),
    ]
