# Generated by Django 4.2.23 on 2025-06-29 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0002_alter_item_options_rename_item_image_item_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='名')),
                ('last_name', models.CharField(max_length=30, verbose_name='姓')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('postal_code', models.CharField(max_length=8, verbose_name='郵便番号')),
                ('prefecture', models.CharField(max_length=10, verbose_name='都道府県')),
                ('city', models.CharField(max_length=50, verbose_name='市区町村')),
                ('address_line1', models.CharField(max_length=100, verbose_name='番地')),
                ('address_line2', models.CharField(blank=True, max_length=100, null=True, verbose_name='建物名・部屋番号')),
                ('card_number', models.CharField(max_length=16, verbose_name='カード番号')),
                ('card_expiry', models.CharField(max_length=5, verbose_name='有効期限(MM/YY)')),
                ('card_cvv', models.CharField(max_length=4, verbose_name='CVV')),
                ('card_holder_name', models.CharField(max_length=100, verbose_name='カード名義人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注文日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('paid', models.BooleanField(default=False, verbose_name='支払済み')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='商品名')),
                ('item_description', models.TextField(blank=True, null=True, verbose_name='商品説明')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品価格')),
                ('item_image', models.URLField(blank=True, null=True, verbose_name='商品画像URL')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注文日時')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.item', verbose_name='商品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='注文')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
    ]
