# Generated by Django 4.2.23 on 2025-06-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(default='', max_length=50, verbose_name='ユーザーネーム'),
            preserve_default=False,
        ),
    ]
