# Generated by Django 4.2.23 on 2025-07-09 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotion_code', '0002_remove_promotioncode_max_uses_promotioncode_is_used_and_more'),
        ('order', '0002_order_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promotion_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='promotion_code.promotioncode', verbose_name='プロモーションコード'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_price',
            field=models.IntegerField(verbose_name='商品価格'),
        ),
    ]
